### ISSUE TITLE
Unable to access data passed through .go

### ISSUE THREAD

**Issue by zeeshan-m** [trazek/ionic-modal-nav-example#2]
I'm passing the data using:

```
IonicModalNavService.go('blah', { id: blah });
```

When the control for that modal initializes this line will run:

```
console.log($stateParams.id);
```

This returns an empty string, rather than undefined. What's being passed into id is a valid integer, rather than an empty string. Any idea what I'm doing wrong here?

**Comment by zeeshan-m** [comment]
Oh, the route in app.js is setup like this:

```
.state('blah', {
  url: '/test/:id',
  views: {
    'ionic-modal-nav@': {
      templateUrl: 'templates/blah.html',
      controller: 'MainCtrl'
    }
  }
})
```

This used to work with $state.go, which is why I tried to use the same syntax with $stateParams.

**Comment by trazek** [comment]
I published a fix for this, thanks for catching it. Following your earlier convention, I added a es5 version in the `src` directory of the module but how you got it to work before will still work. 

Please update and give it a try.

Also, I recommend not putting state params in the url for this case. I intentionally didn't add urls to the modal states in the example repo to avoid populating the main app, in case the url was relied on. You'll probably be ok either way, though.

Thanks!

**Comment by zeeshan-m** [comment]
Just updated, works great now! 

I was having some issued, but then I realized that it was because I was grabbing the es5 file from the dist folder rather than the src folder, probably want to delete that just so theres no confusion. 

Thanks for the tip about removing the URL, I've gone ahead and done that. If anyones reading this later on, you can pass parameters through states without a URL using:

```
.state('app.test', {
  params: {
    'id' : null // Default value goes here
  },
  views: {
    'ionic-modal-nav@': {
      templateUrl: 'templates/test.html',
      controller: 'MainCtrl',
    }
  }
})
```

**Comment by trazek** [comment]
Beautiful. I removed the `dist` folder and published.

Thanks a lot
