### ISSUE TITLE
Displayed darkscreen(or whitescreen) when modal closed by IonicModalService

### ISSUE THREAD

**Issue by jhlee8804** [trazek/ionic-modal-nav-example#6]
I want to IonicModalService library on my sidemenu app, but displayed darkscreen(or whitescreen) when modal closd by IonicModalService and move to previous page. ($ionicModal is works fine)

![bug](https://cloud.githubusercontent.com/assets/8110371/17920970/796e3664-6a12-11e6-830b-5f22f1a090d9.gif)

here my sample code:
https://drive.google.com/file/d/0Bzs8N33JOtOWWk9oazVjbjd2LU0/view?usp=sharing

Thanks.

**Comment by jhlee8804** [comment]
I solved this problem. Please check follow code. It works fine.

```javascript
key: "hide",
value: function hide(data) {
  //this._$ionicHistory.backView(this._backView);
  //this._$ionicHistory.currentView(this._currentView);
  this._$ionicHistory.goBack();  // <-- i added
  this._backView = null;
  this._currentView = null;

  this._$rootScope.$emit(HIDE_MODAL);
  if (data) {
    this._$rootScope.$broadcast(MODAL_CLOSE_DATA, data);
    }
  }
```

**Comment by jhlee8804** [comment]
I solved this problem. Please check this issue. (works fine now)

``` javascript
key: "hide",
value: function hide(data) {
    //this._$ionicHistory.backView(this._backView);
    //this._$ionicHistory.currentView(this._currentView);
    var backCount = -this._$ionicHistory.currentView().index;
    this._$ionicHistory.goBack(backCount - 1);

    this._backView = null;
    this._currentView = null;

    this._$rootScope.$emit(HIDE_MODAL);
    if (data) {
        this._$rootScope.$broadcast(MODAL_CLOSE_DATA, data);
    }
}
```

**Comment by trazek** [comment]
I will look into this and let you know.

**Comment by trazek** [comment]
I added a side nav example to this repo and pushed. I did not update the modal service yet, as I was not able to reproduce the black screen issue. I did encounter that in the beginning but no longer see it. Can you please update with the latest of the example code and see if I properly replicated your use case?

**Comment by jhlee8804** [comment]
hmm... it's strange. Would you please check my sample code again? 
https://drive.google.com/file/d/0Bzs8N33JOtOWWk9oazVjbjd2LU0/view?usp=sharing

My sample project always reproduced issue. If user-agent is android, will be displayed darkscreen, the other user-agent(ios) displayed whitescreen when move to previous page.

**Comment by trazek** [comment]
Sure thing. I will take a look tonight (Eastern standard time)

It could be easier if you created a repo with your sample app, rather than the zip file. But I will check it later tonight regardless.

Thanks for your interest and support

**Comment by trazek** [comment]
I never got around to making this change but created a repo for the service itself:

https://github.com/trazek/ionic-modal-nav

Pull requests welcome. Thanks a lot!
