### ISSUE TITLE
Repo for ionic-modal-nav?

### ISSUE THREAD

**Issue by sinedied** [trazek/ionic-modal-nav-example#7]
Hello,

I could not find the repository for the `ionic-modal-nav` component?
I would like to use this component in my project but with bower, but since you did not publish it on bower I could always add it from git if I could find your repository?

It would also be easier to propose enhancements via PR if it had its own separate repository.

**Comment by trazek** [comment]
Gotcha. That would make it way easier. I'll get that up soon. Thanks for
the feedback

**Comment by trazek** [comment]
Here is the repo. Pull requests welcome. Thanks a lot!

https://github.com/trazek/ionic-modal-nav
